version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      # ensure that a tagged version is fetched
      - git fetch --unshallow || true
      - git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*' || true
      - git fetch --all --tags || true
    pre_create_environment:
        - asdf plugin add uv
        - asdf install uv latest
        - asdf global uv latest
    create_environment:
        - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
        - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync

sphinx:
  configuration: docs/conf.py
