[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
norecursedirs = ["scheil/_dev"]
addopts = "--doctest-modules"
testpaths = [
    "scheil",
    "tests",
]

[tool.setuptools_scm]